/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1a1a1a",
        "on-primary": "#ffffff",
        "primary-container": "#ffcc00",
        "on-primary-container": "#1a1a1a",
        "primary-fixed": "#ffcc00",
        "primary-fixed-dim": "#e6b800",
        secondary: "#e63b2e",
        "on-secondary": "#1a1a1a",
        "secondary-container": "#ffdad6",
        "on-secondary-container": "#1a1a1a",
        "secondary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb3ab",
        tertiary: "#0055ff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d6e3ff",
        "on-tertiary-container": "#1a1a1a",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#a8c6ff",
        background: "#f5f0e8",
        "on-background": "#1a1a1a",
        surface: "#f5f0e8",
        "on-surface": "#1a1a1a",
        "surface-variant": "#e8e3da",
        "on-surface-variant": "#4a4a4a",
        "surface-dim": "#d6d1c9",
        "surface-bright": "#faf7f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2ede5",
        "surface-container": "#eee9e0",
        "surface-container-high": "#e8e3da",
        "surface-container-highest": "#e2ddd4",
        "inverse-surface": "#1a1a1a",
        "inverse-on-surface": "#f5f0e8",
        "inverse-primary": "#f5f0e8",
        outline: "#1a1a1a",
        "outline-variant": "#d0cbc3",
        error: "#cc0000",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#1a1a1a",
        "on-primary-fixed-variant": "#1a1a1a",
        "on-secondary-fixed": "#1a1a1a",
        "on-secondary-fixed-variant": "#1a1a1a",
        "on-tertiary-fixed": "#1a1a1a",
        "on-tertiary-fixed-variant": "#1a1a1a",
        "surface-tint": "#1a1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      animation: {
        "bounce-delay-1": "bounce 1s infinite -0.3s",
        "bounce-delay-2": "bounce 1s infinite -0.15s",
      },
    },
  },
  plugins: [],
}
